// client/pages/settings/settings-page.svelte
<script lang="ts">
  import { auth, user$ } from '@/shared/lib'
  import { Link } from 'svelte-routing'
</script>

<h1>Settings</h1>

<div class="mt-8">
  {#if $user$?.role === 'admin'}
    <div>
      <Link to="/admin">admin</Link>
    </div>
  {/if}

  <button class="mt-4" on:click={auth.logout}>Logout</button>
</div>

// client/pages/settings/settings-page.vue
<script setup lang="ts">
import { useAuth, auth as action } from '@/shared/lib'

const { user } = useAuth()
</script>

<template>
  <h1>Settings</h1>

  <div class="mt-8">
    <div v-if="user?.role === 'admin'">
      <RouterLink to="/admin"> admin </RouterLink>
    </div>

    <button class="mt-4" @click="action.logout">Logout</button>
  </div>
</template>
