// client/pages/home/home-page.svelte
<script lang="ts">
  import { user$ } from '@/shared/lib'
  import { series, SeriesItem } from '@/entities/series'
  import { movies, MovieItem } from '@/entities/movie'
  import { Spinner } from '@/shared/ui'
  import { onMount } from 'svelte'

  onMount(() => {
    series.refresh()
    movies.refresh()
  })
</script>

<h1>Series</h1>

<p class="mt-8">User: {$user$?.username}</p>

<p>Role: {$user$?.role}</p>

<p>All Series</p>

{#if series.isLoading}
  <Spinner size={24} />
{/if}

<ul>
  {#each series.all as item (item.id)}
    <li>
      <SeriesItem series={item} />
    </li>
  {/each}
</ul>

<p>All Movies</p>

{#if movies.isLoading}
  <Spinner size={24} />
{/if}

<ul>
  {#each movies.all as movie (movie.id)}
    <li>
      <MovieItem {movie} />
    </li>
  {/each}
</ul>

// client/pages/home/home-page.vue
<script setup lang="ts">
import { onBeforeMount } from 'vue'
import { useSeries, SeriesItem } from '@/entities/series'
import { useMovies, MovieItem } from '@/entities/movie'
import { Spinner } from '@/shared/ui'
import { useHome } from './model'

const home = useHome()
const series = useSeries()
const movies = useMovies()

onBeforeMount(() => {
  series.refresh()
  movies.refresh()
})
</script>

<template>
  <h1>Home</h1>

  <div class="flex gap-4">
    <button class="secondary" :class="{ selected: home.forMe }" @click="home.toggleForMe">For Me</button>
    <button @click="home.toggleSort">By {{ home.sort }}</button>
  </div>

  <p class="mt-8">All Series</p>

  <Spinner v-if="series.isLoading && !home.series.length" :size="24" />

  <ul>
    <li v-for="item in home.series" :key="item.id" class="mt-4">
      <SeriesItem :series="item" />
    </li>
  </ul>

  <p class="mt-8">All Movies</p>

  <Spinner v-if="movies.isLoading && !home.movies.length" :size="24" />

  <ul>
    <li v-for="movie in home.movies" :key="movie.id" class="mt-4">
      <MovieItem :movie />
    </li>
  </ul>

  <router-view />
</template>
