// client/pages/home/search-dialog.svelte
<script lang="ts">
  import { Link, navigate } from 'svelte5-router'
  import { api, type SearchItem } from '@/shared/api'
  import { focusOnMount, preventDefault } from '@/shared/lib'
  import { Item, Spinner } from '@/shared/ui'

  let query = $state('')
  let isSearching = $state(false)
  let result = $state<SearchItem[] | null>(null)

  const series = $derived(result?.filter((item) => item.type === 'series') ?? [])
  const movies = $derived(result?.filter((item) => item.type === 'movie') ?? [])
  const omdbId = /^tt\d+/

  const search = async () => {
    query = query.trim()

    if (query.match(omdbId)) {
      return navigate(`/edit/${query}`)
    }

    isSearching = true
    result = null

    try {
      result = await api.search.external(query)
    } catch {
      result = []
    } finally {
      isSearching = false
    }
  }
</script>

<form class="sticky top-0 w-full" onsubmit={preventDefault(search)}>
  <input
    class="w-full"
    type="text"
    name="q"
    bind:value={query}
    placeholder="Search..."
    disabled={isSearching}
    use:focusOnMount
  />
</form>

{#if isSearching}
  <div class="mt-6 text-center">
    <Spinner size={24} />
  </div>
{/if}

{#if result?.length}
  {#if series.length}
    <h3 class="mt-8">Series</h3>
    <ul class="mt-4 flex flex-col gap-4">
      {#each series as item}
        <li>
          <Link class="not-link" to={`/edit/${item.id}`}>
            <Item title={item.title} description={item.year ? String(item.year) : null} imgUrl={item.poster} />
          </Link>
        </li>
      {/each}
    </ul>
  {/if}

  {#if movies.length}
    <h3 class="mt-8">Movies</h3>
    <ul class="mt-4 flex flex-col gap-4">
      {#each movies as item}
        <li>
          <Link class="not-link" to={`/edit/${item.id}`}>
            <Item title={item.title} description={item.year ? String(item.year) : null} imgUrl={item.poster} />
          </Link>
        </li>
      {/each}
    </ul>
  {/if}
{:else if result}
  Nothing was found
{/if}

<style>
  form {
    background-color: var(--card);
  }
</style>

// client/pages/home/search-dialog.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { api, type SearchItem } from '@/shared/api'
import { Dialog, Item, Spinner } from '@/shared/ui'
import { vFocusOnMount } from '@/shared/lib'
import { useRouter } from 'vue-router'

const router = useRouter()

const query = ref('')
const isSearching = ref(false)
const result = ref<SearchItem[] | null>(null)

const series = computed(() => result.value?.filter((item) => item.type === 'series') ?? [])
const movies = computed(() => result.value?.filter((item) => item.type === 'movie') ?? [])
const omdbId = /^tt\d+/

const search = async () => {
  query.value = query.value.trim()

  if (query.value.match(omdbId)) {
    return router.push(`/add/${query.value}`)
  }

  isSearching.value = true
  result.value = null

  try {
    result.value = await api.search.external(query.value)
  } catch {
    result.value = []
  } finally {
    isSearching.value = false
  }
}
</script>

<template>
  <Dialog id="search">
    <form class="sticky top-0 w-full" @submit.prevent="search">
      <input
        class="w-full"
        type="text"
        name="q"
        v-model="query"
        placeholder="Search..."
        :disabled="isSearching"
        v-focus-on-mount
      />
    </form>

    <div v-if="isSearching" class="mt-6 text-center">
      <Spinner :size="24" />
    </div>

    <template v-if="series.length">
      <h3 class="mt-8">Series</h3>
      <ul class="mt-4 flex flex-col gap-4">
        <li v-for="item in series" :key="item.id">
          <RouterLink class="not-link" :to="`/add/${item.id}`" :data-testid="`search-series-${item.id}`">
            <Item :title="item.title" :description="item.year ? String(item.year) : null" :imgUrl="item.poster" />
          </RouterLink>
        </li>
      </ul>
    </template>

    <template v-if="movies.length">
      <h3 class="mt-8">Movies</h3>
      <ul class="mt-4 flex flex-col gap-4">
        <li v-for="item in movies" :key="item.id">
          <RouterLink class="not-link" :to="`/add/${item.id}`" :data-testid="`search-movie-${item.id}`">
            <Item :title="item.title" :description="item.year ? String(item.year) : null" :imgUrl="item.poster" />
          </RouterLink>
        </li>
        {/each}
      </ul>
    </template>
  </Dialog>
</template>

<style scoped>
form {
  background-color: var(--card);
}
</style>
